version: '3.9'

volumes:
  server-1-data:
  server-2-data:
  server-3-data:
  server-config-data:
  server-4-data:
  server-5-data:
  client-1-data:
  client-2-data:
  prometheus-data:

x-template: &template
  image: consul:latest
  healthcheck:
    test: [ "CMD", "curl", "http://localhost:8500" ]
    interval: 5s
    timeout: 10s
    retries: 5

services:

  server-1:
    <<: *template
    volumes:
      - server-1-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-1:/consul/config:ro
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/server.sh paris
    ports:
      - 8500:8500 # UI
      - 8600:8600 # DNS
      - 8600:8600/udp # DNS

  server-2:
    <<: *template
    depends_on:
      - server-1
    volumes:
      - server-2-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-2:/consul/config:ro
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/server.sh paris

  server-3:
    <<: *template
    depends_on:
      - server-2
    volumes:
      - server-3-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-3:/consul/config:ro
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/server.sh paris

  server-config:
    <<: *template
    depends_on:
      - server-1
      - server-2
      - server-3
    volumes:
      - server-config-data:/consul/data
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/config.sh

  client-1:
    <<: *template
    depends_on:
      - server-config
    volumes:
      - client-1-data:/consul/data
      - ./config/certs:/consul/certs
      - ./config/client-1:/consul/config
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/client.sh

  client-2:
    <<: *template
    depends_on:
      - server-5
    volumes:
      - client-2-data:/consul/data
      - ./config/certs:/consul/certs
      - ./config/client-2:/consul/config
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/client.sh

  server-4:
    <<: *template
    depends_on:
      - server-3
    volumes:
      - server-4-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-4:/consul/config:ro
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/server.sh seclin

  server-5:
    <<: *template
    depends_on:
      - server-4
    volumes:
      - server-5-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-5:/consul/config:ro
      - ./config/scripts:/consul/scripts:ro
    command: /consul/scripts/server.sh seclin

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=http://localhost:9090/prometheus/"
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /:/host:ro,rslave
    pid: host
    command:
      - --path.rootfs=/host
      - --web.listen-address=:9100

  traefik:
    image: traefik:latest
    volumes:
      - ./config/traefik.toml:/etc/traefik/traefik.toml:ro
    ports:
      - 80:80
      - 8080:8080

  whoami-1:
    image: traefik/whoami:latest
    ports:
      - 8081:80

  whoami-2:
    image: traefik/whoami:latest
    ports:
      - 8082:80
