version: '3.9'

volumes:
  server-1-data:
  server-2-data:
  server-3-data:
  server-4-data:
  server-5-data:
  client-1-data:
  client-2-data:

x-template: &template
  image: consul:latest
  healthcheck:
    test: [ "CMD", "curl", "http://localhost:8500" ]
    interval: 5s
    timeout: 10s
    retries: 5

services:

  server-1:
    <<: *template
    volumes:
      - server-1-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-1:/consul/config:ro
      - ./config/server.sh:/consul/server.sh:ro
    command: /consul/server.sh paris
    ports:
      - 8500:8500

  server-2:
    <<: *template
    depends_on:
      - server-1
    volumes:
      - server-2-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-2:/consul/config:ro
      - ./config/server.sh:/consul/server.sh:ro
    command: /consul/server.sh paris

  server-3:
    <<: *template
    depends_on:
      - server-2
    volumes:
      - server-3-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-3:/consul/config:ro
      - ./config/server.sh:/consul/server.sh:ro
    command: /consul/server.sh paris

  server-config:
    <<: *template
    depends_on:
      - server-1
      - server-2
      - server-3
    volumes:
      - ./config/config.sh:/consul/config.sh:ro
    command: /consul/config.sh

  client-1:
    <<: *template
    depends_on:
      - server-config
    volumes:
      - client-1-data:/consul/data
      - ./config/certs:/consul/certs
      - ./config/client-1:/consul/config
      - ./config/client.sh:/consul/client.sh:ro
    command: /consul/client.sh

  client-2:
    <<: *template
    depends_on:
      - server-config
    volumes:
      - client-2-data:/consul/data
      - ./config/certs:/consul/certs
      - ./config/client-2:/consul/config
      - ./config/client.sh:/consul/client.sh:ro
    command: /consul/client.sh

  server-4:
    <<: *template
    depends_on:
      - server-3
    volumes:
      - server-4-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-4:/consul/config:ro
      - ./config/server.sh:/consul/server.sh:ro
    command: /consul/server.sh seclin

  server-5:
    <<: *template
    depends_on:
      - server-4
    volumes:
      - server-5-data:/consul/data
      - ./config/certs:/consul/certs:ro
      - ./config/server-5:/consul/config:ro
      - ./config/server.sh:/consul/server.sh:ro
    command: /consul/server.sh seclin
