# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: 'client-1:8500'
        token: '6a414ac2-850f-7921-2ba2-141ee456f966'
        datacenter: 'paris'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,monitoring,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: ['__meta_consul_node']
        replacement: '$1'
        target_label: instance
      - source_labels: ['__meta_consul_service_metadata_path']
        regex: (.+)
        replacement: $1
        target_label: __metrics_path__
